# Generated by Django 6.0 on 2025-12-06 15:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_content_ar_article_content_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[(app.models.SocialPlatform['WHATSAPP'], 'WhatsApp'), (app.models.SocialPlatform['FACEBOOK'], 'Facebook'), (app.models.SocialPlatform['X'], 'X'), (app.models.SocialPlatform['INSTAGRAM'], 'Instagram'), (app.models.SocialPlatform['TELEGRAM'], 'Telegram'), (app.models.SocialPlatform['YOUTUBE'], 'YouTube')], default=app.models.SocialPlatform['WHATSAPP'], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
