# Generated by Django 6.0 on 2025-12-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_ar',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_de',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_zh',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_ar',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_de',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_es',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_zh',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_ar',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_de',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_es',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_zh',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slug_ar',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slug_de',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slug_es',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slug_zh',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_ar',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_de',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_es',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_zh',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
