# Generated by Django 6.0 on 2025-12-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_article_slug_ar_article_slug_de_article_slug_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_zh',
            new_name='content_zh_hans',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='slug_zh',
            new_name='slug_zh_hans',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title_zh',
            new_name='title_zh_hans',
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='name_zh',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='slug_zh',
            new_name='slug_zh_hans',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_zh',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='slug_zh',
            new_name='slug_zh_hans',
        ),
        migrations.RenameField(
            model_name='investmentobject',
            old_name='description_zh',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='investmentobject',
            old_name='title_zh',
            new_name='title_zh_hans',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='content_zh',
            new_name='content_zh_hans',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='slug_zh',
            new_name='slug_zh_hans',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='title_zh',
            new_name='title_zh_hans',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description_zh',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='slug_zh',
            new_name='slug_zh_hans',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title_zh',
            new_name='title_zh_hans',
        ),
    ]
